# Generated by Django 2.0.7 on 2018-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180720_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_applied',
            field=models.DateField(blank=True, verbose_name='applied'),
        ),
    ]
