# Generated by Django 2.0.7 on 2018-07-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20180720_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='job',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='response'),
        ),
    ]
