# Generated by Django 2.0.7 on 2018-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20180724_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='job',
            name='response',
            field=models.TextField(blank=True, default='', verbose_name='response'),
        ),
    ]
