# Generated by Django 2.0.7 on 2018-10-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20180724_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_state',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Rejected', 'Rejected'), ('Wishlist', 'Wishlist'), ('Phone interview', 'Phone interview'), ('Office interview', 'Office interview'), ('Offer', 'Offer')], max_length=20, verbose_name='application_state'),
        ),
    ]
