# Generated by Django 2.0.7 on 2018-10-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20181001_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date_applied'], 'verbose_name': 'Job description'},
        ),
    ]
